### ISSUE TITLE
Describe how to use this with jupyter lab

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/jupyter-panel-proxy#10]
I am trying to use this with Jupyterlab. I have `jupyter-panel-proxy` installed.

I am using this repository https://github.com/marcskovmadsen/load-forecasts

I am starting `jupyter lab` from the root of the repository.

I can open the file `notebooks/app.py` in jupyter lab at http://localhost:8889/lab/workspaces/auto-7/tree/notebooks/app.py

![image](https://user-images.githubusercontent.com/42288570/110248146-eda45780-7f6f-11eb-8cc4-09614107b096.png)

But if I open 

- http://localhost:8889/lab/workspaces/auto-7/tree/panel/notebooks/app.py or 
- http://localhost:8889/lab/workspaces/auto-7/tree/notebooks/panel/app.py 
- http://localhost:8889/lab/workspaces/auto-7/tree/notebooks/app.py?urlpath=/panel/app.py
- - http://localhost:8889/lab/workspaces/auto-7/tree/notebooks/app.py?urlpath=/panel/notebooks/app.py

it just redirects to the original url 

- http://localhost:8889/lab/workspaces/auto-7/tree/notebooks/app.py 
- 
- in jupyter lab.

**Comment by WesleyTheGeolien** [comment]
@MarcSkovMadsen It looks like this is setup to handle ipynb and note .py files. I have just added a PR #11 to the repo that _should_ allow serving python files
