### ISSUE TITLE
Migrate travis workflow to GitHub Actions

### ISSUE THREAD

**Issue by WesleyTheGeolien** [holoviz/jupyter-panel-proxy#12]
#### Is your feature request related to a problem? Please describe.
Travis is _outdated_ we could migrate the workflow to GitHub actions instead

#### Describe the solution you'd like
Use GitHub Actions instead of Travis CI

#### Describe alternatives you've considered
Change nothing

**Comment by WesleyTheGeolien** [comment]
Opening this after conversation with @philippjfr in #11.

I can take a look at doing the migration and create a PR If that is ok with everyone

**Comment by philippjfr** [comment]
@WesleyTheGeolien That would be great. If not I'll try to pick it up over the weekend.

**Comment by philippjfr** [comment]
Sorry, @WesleyTheGeolien this fell completely off my radar and I've revived it in https://github.com/holoviz/jupyter-panel-proxy/pull/17
